---
# tasks file for ansible-role-aws-security-groups

- name: Create security groups
  ec2_group:
    name: "{{ environ }}-{{ item.service_name }}"
    description: "Security group for the {{ environ }}-{{ item.service_name }}"
    aws_access_key: "{{lookup('env','AWS_ACCESS_KEY_ID')}}"
    aws_secret_key: "{{lookup('env','AWS_SECRET_ACCESS_KEY')}}"
    vpc_id: "{{ item.aws_acct_vpc_id }}"
    region: "{{ item.aws_region | default('us-west-2') }}"
    rules:
      - proto: "{{ item.ingress_proto }}"
        from_port: "{{ item.ingress_from_port }}"
        to_port: "{{ item.ingress_to_port }}"
        cidr_ip: "{{ item.ingress_cidr_ip }}"
    rules_egress:
      - proto: "{{ item.egress_proto }}"
        from_port: "{{ item.egress_from_port | default(omit) }}"
        to_port: "{{ item.egress_to_port | default(omit) }}"
        cidr_ip: "{{ item.egress_cidr_ip | default('0.0.0.0/0') }}"
  with_items: sg_settings
